### ISSUE TITLE
An error occured when reading a module

### ISSUE THREAD

**Issue by kjirou** [azu/espower-babel#2]
An error occured in the following case.

`test/demo_test.js` 

```
let getFoo = require('../lib/get-foo');

let assert = require('power-assert')
// .. Same as the README
```

`lib/get-foo.js`

```
export default function getFoo() {
  return 'foo';
}
```

```
$ mocha --compilers js:espower-babel/guess test/demo_test.js

/Users/kjirou/working/test-espower-babel/lib/get-foo.js:1
(function (exports, require, module, __filename, __dirname) { export default f
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.extensions..js (/Users/kjirou/working/test-espower-babel/node_modules/espower-babel/index.js:20:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kjirou/working/test-espower-babel/test/demo_test.js:14:14)
    at Module._compile (module.js:456:26)
    at Object.extensions..js (/Users/kjirou/working/test-espower-babel/node_modules/espower-babel/index.js:18:25)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/kjirou/working/test-espower-babel/node_modules/mocha/lib/mocha.js:185:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/kjirou/working/test-espower-babel/node_modules/mocha/lib/mocha.js:182:14)
    at Mocha.run (/Users/kjirou/working/test-espower-babel/node_modules/mocha/lib/mocha.js:394:31)
    at Object.<anonymous> (/Users/kjirou/working/test-espower-babel/node_modules/mocha/bin/_mocha:394:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

module versions:

```
"devDependencies": {
  "babel": "4.6.6",
  "espower-babel": "1.3.0",
  "mocha": "2.1.0",
  "power-assert": "0.10.2"
}
```

**Comment by azu** [comment]
This is intended result.

> $ mocha --compilers js:espower-babel/guess test/demo_test.js

espower-babel doesn't treat `lib/*.js`. it cover only `test/demo_test.js` in this case.

espower-babel can convert files that are match `test/demo_test.js`.
https://github.com/azu/espower-babel/blob/fa82e9e6b4bc68b3758dc52c083e016cde95cdd9/index.js#L15-L18

Thanks report and pull requests are welcome!

**Comment by kjirou** [comment]
I could understand.

Thanks!
