### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by kazupon** [azu/espower-babel#26]
- version
  espower-babel@4.0.3
- reproduction repo (branch)
  https://github.com/vuejs/vue-validator/tree/espower-babel
- reproduction procedure

``` shell
$ npm install
$ npm run e2e
```
- error details

```
/Users/kazupon/Projects/opensource/vue/vue-validator/test/e2e/test.js:3
import assert from 'power-assert';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.extensions.(anonymous function) [as .js] (/Users/kazupon/Projects/opensource/vue/vue-validator/node_modules/espower-babel/index.js:66:25)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/kazupon/Projects/opensource/vue/vue-validator/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/kazupon/Projects/opensource/vue/vue-validator/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/Users/kazupon/Projects/opensource/vue/vue-validator/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/Users/kazupon/Projects/opensource/vue/vue-validator/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```
- environments (node_modules)

```
vue-validator@2.0.0 /Users/kazupon/Projects/opensource/vue/vue-validator
├── babel-core@6.7.4
├── babel-loader@6.2.4
├── babel-plugin-espower@2.1.2
├── babel-plugin-rewire@1.0.0-rc-1
├── babel-plugin-transform-es2015-modules-commonjs@6.7.4
├── babel-polyfill@6.7.4
├── babel-preset-es2015@6.6.0
├── babel-preset-es2015-loose@7.0.0
├── babel-preset-es2015-loose-rollup@1.0.0 (git+https://github.com/kazupon/babel-preset-es2015-loose-rollup.git#98b11e656324ba762e36c65cf0aa8e2735fecb9a)
├── babel-preset-es2015-rollup@1.1.1
├── cz-conventional-changelog@1.1.5
├── eslint@2.7.0
├── eslint-config-standard@5.1.0
├── eslint-loader@1.3.0
├── eslint-plugin-promise@1.1.0
├── eslint-plugin-standard@1.3.2
├── espower-babel@4.0.3
├── istanbul-instrumenter-loader@0.2.0
├── json-loader@0.5.4
├── karma@0.13.22
├── karma-chrome-launcher@0.2.2
├── karma-coverage@0.5.5
├── karma-coveralls@1.1.2
├── karma-firefox-launcher@0.1.7
├── karma-mocha@0.2.2
├── karma-mocha-reporter@2.0.0
├── karma-phantomjs-launcher@0.2.3
├── karma-safari-launcher@0.1.1
├── karma-sauce-launcher@0.3.1
├── karma-sourcemap-loader@0.3.7
├── karma-webpack@1.7.0
├── mocha@2.4.5
├── mocha-generators@1.2.0
├── mocha-loader@0.7.1
├── nightmare@2.2.0
├── phantomjs@2.1.3
├── power-assert@1.3.1
├── rollup@0.25.4
├── rollup-plugin-babel@2.4.0
├── rollup-plugin-replace@1.1.0
├── sinon@1.17.3
├── uglify-js@2.6.2
├── vue@1.0.20
├── webpack@1.12.14
└── webpack-dev-server@1.14.1
```

**Comment by azu** [comment]
Babel no have config then throw this error.

Currently espower-babel's benefit is thin, because espower-babel + Babel 6 require `.babelrc`.
You can use directly [babel-plugin-espower](https://github.com/power-assert-js/babel-plugin-espower).

**Comment by kazupon** [comment]
@azu 
Thanks!! I could resolve. :smile_cat:
